### ISSUE TITLE
I am a fan 

### ISSUE THREAD

**Issue by eliecer2000** [adiintify/adiintify#1]
Hi I read your post, 
https://spoofing.medium.com/deploying-applications-to-ecs-fargate-with-aws-cdk-and-typescript-c0b5acdcb1d7

and it was what I was looking for. I couldn't fit all the pieces together.

Can you give me the link to the repository where the complete project is.

Thank you.

**Comment by adiintify** [comment]
Hi @eliecer2000,

I have invited you as a collaborator. 

Thanks!
